baseURL = 'https://pellepelster.github.io/solidblocks/'
languageCode = 'en-us'
title = 'Solidblocks'
theme = "relearn"

[params]
    themeVariant = "green"

[security]
[security.funcs]
getenv = ['.*_VERSION$', '.*_CHECKSUM$']