baseURL = 'https://pellepelster.github.io/solidblocks/'
languageCode = 'en-us'
title = 'Solidblocks'
theme = "relearn"

[params]
themeVariant = "green"
editURL = "https://github.com/pellepelster/solidblocks/tree/main/doc/content/"
canonifyURLs = true
relativeURLs = true

[security]
[security.funcs]
getenv =['.*_VERSION$', '.*_CHECKSUM$']

[outputs]
home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]