name: solidblocks

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: solidblocks
  cancel-in-progress: false

permissions:
  pages: write
  id-token: write
  contents: write
  packages: write

jobs:
  solidblocks-shell:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: solidblocks-shell/do build
      - name: Test
        run: solidblocks-shell/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-shell
          path: |
            solidblocks-shell/build/solidblocks-shell-*.zip
            solidblocks-shell/build/documentation/shell_bootstrap_solidblocks
            solidblocks-shell/build/documentation/shell_minimal_skeleton_do

  solidblocks-minio:
    name: solidblocks-minio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: solidblocks-minio/do build
      - name: Test
        run: solidblocks-minio/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-minio
          path: |
            solidblocks-minio/build/solidblocks-minio-*.tar
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-minio-test
          path: |
            solidblocks-minio/test/build/reports/tests

  solidblocks-debug-container:
    name: solidblocks-debug-container
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: solidblocks-debug-container/do build
      - name: Test
        run: solidblocks-debug-container/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-debug-container
          path: |
            solidblocks-debug-container/build/solidblocks-debug-container-*.tar
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-debug-container-test
          path: |
            solidblocks-debug-container/build/reports/tests

  solidblocks-rds-postgresql:
    name:  solidblocks-rds-postgresql
    runs-on: ubuntu-latest
    needs:
      - solidblocks-minio
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Minio Docker Image
        uses: actions/download-artifact@v3
        with:
          name: solidblocks-minio
          path: /tmp
      - name: Import Minio Docker Image
        run: docker load < /tmp/solidblocks-minio-*.tar
      - name: Build
        run: solidblocks-rds-postgresql/do build
      - name: Test
        run: solidblocks-rds-postgresql/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-rds-postgresql
          path: |
            solidblocks-rds-postgresql/build/solidblocks-rds-postgresql-*.tar
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-rds-postgresql-test
          path: |
            solidblocks-rds-postgresql/test/build/reports/tests

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - solidblocks-shell
      - solidblocks-minio
      - solidblocks-rds-postgresql
      - solidblocks-debug-container
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Import Minio Docker Image
        run: docker load < solidblocks-minio/solidblocks-minio-*.tar
      - name: Import RDS Postgresql Docker Image
        run: docker load < solidblocks-rds-postgresql/solidblocks-rds-postgresql-*.tar
      - name: Import Debug Container Docker Image
        run: docker load < solidblocks-debug-container/solidblocks-debug-container-*.tar
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release Docker
        run: ./do release-docker
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            solidblocks-shell/solidblocks-shell-*.zip
            solidblocks-shell/documentation/*


  documentation:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Set SOLIDBLOCKS_SHELL_CHECKSUM
        run: echo "SOLIDBLOCKS_SHELL_CHECKSUM=$(sha256sum solidblocks-shell/solidblocks-shell-*.zip | head -1 | awk '{ printf  "%1s", $1 }')" >> $GITHUB_ENV

      - name: Build Documentation
        run: ./do build-documentation
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/documentation'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

